import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeroUiProvider } from "./Providers/HerouiProvider";
import Navbar from "@/components/modules/navbar/Navbar";
import { ThemeProvider } from "next-themes";
import { ShootingStars } from "@/components/modules/shootingStars/shooting-stars";
import {
  ClerkProvider
} from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} bg-[#ededed] text-black antialiased dark:bg-[#0a0a0a] dark:text-white`}
        > 
          <ThemeProvider attribute="class">
            <Navbar />
            <HeroUiProvider>
              <div className="relative z-50">{children}</div>
            </HeroUiProvider>
            <ShootingStars />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
