import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeroUiProvider } from "../../Providers/HerouiProvider";
import Navbar from "@/components/modules/navbar/Navbar";
import { ThemeProvider } from "next-themes";
import { ShootingStars } from "@/components/modules/shootingStars/shooting-stars";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import localFont from "next/font/local";

import en from "../../../messages/en.json";
import fa from "../../../messages/fa.json";

export const vazirmatn = localFont({
  src: [
    {
      path: "../../fonts/vazir/Vazir-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../fonts/vazir/Vazir-Medium.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../fonts/vazir/Vazir-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-vazir",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  console.log(locale);

  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
      localization={locale === "en" ? en : fa}
    >
      <html lang={locale}>
        <body
          className={`${vazirmatn.variable} bg-[#ededed] text-black antialiased dark:bg-[#0a0a0a] dark:text-white`}
        >
          <ThemeProvider attribute="class">
            <NextIntlClientProvider locale={locale} messages={messages}>
              <Navbar />
              <HeroUiProvider>
                <div
                  className={`relative z-50 ${locale === "fa" ? "font-vazir" : ""}`}
                >
                  {children}
                </div>
              </HeroUiProvider>
              <ShootingStars />
            </NextIntlClientProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
